---
# tasks file for ansible-role-jumphost
- name: Ensure jumphost .ssh directory exists
  ansible.builtin.file:
    path: "{{ jumphost_ssh_dir }}"
    state: directory
    owner: "{{ jumphost_user }}"
    group: "{{ jumphost_user }}"
    mode: "0700"

- name: Create the jumphost ssh config
  ansible.builtin.template:
    src: ssh.config.j2
    dest: "{{ jumphost_ssh_config_path }}"
    owner: "{{ jumphost_user }}"
    group: "{{ jumphost_user }}"
    mode: "0600"
