---

version: 2

workflows:
  version: 2
  ansible_review_and_test:
    jobs:
      - ansible_review

jobs:
  ansible_review:
    working_directory: ~/ansible-role-jumphost
    docker:
      - image: circleci/python:3.6.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - setup_remote_docker
      - run:
          command: |
            pipenv run molecule test
