---

version: 2

workflows:
  version: 2
  ansible_review_and_test:
    jobs:
      - ansible_review

jobs:
  ansible_review:
    working_directory: ~/ansible-role-jumphost
    docker:
      - image: cimg/python:3.12.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: pipenv install --dev
      - setup_remote_docker
      - run: sudo apt update; sudo apt install rsync
      - run: pipenv run molecule destroy
      - run: pipenv run molecule test
