---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux:8
    cgroupns: host
  - name: otherhost
    image: rockylinux:8
    cgroupns: host
provisioner:
  name: ansible
  log: true
  inventory:
    links:
      hosts: inventory
  playbooks:
    converge: playbook.yml
verifier:
  name: testinfra
